### ISSUE TITLE
Taking opponents capital doesn't remove the garrison and possible ships in port.

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#108]
![image](https://user-images.githubusercontent.com/22304202/72346321-08659e00-36d6-11ea-9f2b-374afeb6116d.png)

In fact the question "Do you want to overtake the ships or kill them" is completely missing.

**Comment by Longwelwind** [comment]
Restrictions of ports are not fully implemented yet, atm the only implemented things are the inability of a port to support the adjacent land, and the restriction that a house can't enter an enemy-controlled port. I'll close this issue since the first issue (garrison tokens not being removed) is fixed, and make a comment in #2 to keep track of the bugs.
