### ISSUE TITLE
Combat strength does not update when changing house card after confirming one.

### ISSUE THREAD

**Issue by mrhappyasthma** [Longwelwind/swords-and-ravens#1229]
Repro steps:

- Select a house card in combat and confirm.
- Then select a different card and re-confirm
- Observe the values don't update (`House Card` or `Total`)

![5TXW9xT4qHGarsY](https://user-images.githubusercontent.com/1547356/138164165-9173649c-0de4-4bca-aaf9-318ac85a9a57.png)

**Comment by gereon77** [comment]
Hi @mrhappyasthma 

This is by design and the game never updated the house card / total value during choose house cards before. This is because the combat info dialog uses the `HouseCombatData` from CombatGameState to calculate the strengths and the house cards there are set after both cards are chosen.
