### ISSUE TITLE
"Domestic Disputes" only permits one capital selection.

### ISSUE THREAD

**Issue by alecejones-noodoe** [Longwelwind/swords-and-ravens#1449]
When using "Domestic Disputes" in Mother of Dragons, Targaryen player is only allowed to select one capital city instead of up to four as the card suggests is possible. The images below will illustrate.

![194373](https://user-images.githubusercontent.com/66933415/162926330-323f0e7f-35a6-45ef-a6c6-3af752032318.jpg)
![194374](https://user-images.githubusercontent.com/66933415/162926097-14953f25-e3e2-4d73-bdd9-53c87c80e7b4.jpg)
![194375](https://user-images.githubusercontent.com/66933415/162926138-c4287da9-2105-4bf8-9611-102ecc9dc451.jpg)

**Comment by gereon77** [comment]
The game asks if you want to place another one if there are still some LTs available. Remember there is a max of 20 LTs.

**Comment by gereon77** [comment]
![image](https://user-images.githubusercontent.com/22304202/163054519-b19e79eb-e48e-487a-b3be-0f6e39e2a305.png)
just happened in https://swordsandravens.net/play/274e481b-7083-4bdc-abfc-28c912d7a598

**Comment by alecejones-noodoe** [comment]
Here's the game link here: https://swordsandravens.net/play/21a54d6b-b4d6-433c-a917-3d2349ff4ee5

The Targ player has not used 20 tokens. As you can see from the photos, the player is presented with a choice of all capitals. When Sunspear is selected, the other capitals deselect, and the player cannot choose others. So he has enough tokens to use and has not chosen 'No', but the game does not permit more than one additional city to be chosen.

**Comment by gereon77** [comment]
The workflow is to choose one by one. This is done because we have no `SelectRegionsGameState` and I was too lazy to create one.

So I used the existing SelectSingleRegion state , where all capitals are selected but you can just select one. After confirmation the game asks if you want to place another one (if able)  or if you want to end placing. The card text says „may place in up to 4“ which means to me you should be able to place less than 4 as well.

Therefore, if 20 was not reached, the Targ player must have chosen to end placing after he has chosen his first capital.
