### ISSUE TITLE
Raven holder should be able to remember the seen wildling card after he used the raven

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#245]
This idea came to my mind as in one of my home games the raven holder took a photo of the top wildling card. As many games will be PBEM we should implement that also here.

@Longwelwind  Do you intend to implement this? And what solution would you prefer: „General Game notes“ which would allow to notice other things like future plans, betrayals, etc. Or enabling viewing last seen card at any time which would allow checking also all effects again without knowing each card by heart.

**Comment by Dode123** [comment]
I have already burned myself on this a couple of times! Would be a welcome QOL change 😊

**Comment by norielbit** [comment]
A possible implementation for this came up recently, where the last seen card will be displayed as part of the Wildling Threat icon tooltip

**Comment by Longwelwind** [comment]
The big question to solve for this is how to save the last card that was seen by the Raven holder. One possible way is to have variable `canRavenHolderKnowNextCard` (in `IngameGameState` or `Game`), to have it set to `true` when the card is revelead, and set it to `false` when it changes.

When we serialize the game, we only send the top of the wildling card to the Raven Holder if the variable is set to true. The UI can then display it accordingly.

**Comment by gereon77** [comment]
That is almost the solution I‘d have suggested. But your version doesn’t  respect the fact that the raven holder can change in between. So I guess we need a variable on the player itself if he can see the upcoming wildlings card. It then could be shown as tooltip when hovering over the wildlings symbol.

**Comment by norielbit** [comment]
I agree with @gereon77's approach of having it House-based, I think I'll start working on it.
The `knowsNextWildlingCard` should be updated only when one of the following occurs, right?
- Raven holder peeks at the card and keeps it: Set Raven holder to true
- Raven holder peeks at the card and switches it: Set everyone to false
- Wildling attack resolved: Set everyone to false

I think also keeping what is the last card when the Raven holder chooses to switch it is of some interest as well. At some cases knowing what the wildling card isn't is as important as what it is. It's a less important issue that should be solved in a different issue with a different solution.
Just as a suggestion if/when for that, I think the best way to keep it is through the game log (let whoever was the Raven Holder see what card he saw and at what time), so that the information exists when its needed but doesn't clutter the UI for the 90% where it isn't.

**Comment by Longwelwind** [comment]
`knowsNextWildlingCard` in `Player` sounds good to me!

> Just as a suggestion if/when for that, I think the best way to keep it is through the game log (let whoever was the Raven Holder see what card he saw and at what time), so that the information exists when its needed but doesn't clutter the UI for the 90% where it isn't.

Yup.

To implement this, we would need to add _secret_ game logs that are only available to a set of players.

**Comment by norielbit** [comment]
Should the `knowsNextWildlingCard` parameter be in `Player`, or `House`? Of course its a nitpick, but it seems to me that `Player` is somewhat disconnected from the game logic itself so it would make sense to put it in `House`. For now I'll put it in `Player` unless you guys say otherwise.

**Comment by Longwelwind** [comment]
`Player` was at first supposed to be disconnected from the game logic, but it will be anyway with Vassals, since there must a clear distinction between a player-owned house and a vassal.

I'd still put it in `Player`. 🙂

**Comment by norielbit** [comment]
I experimented with both while coding, I liked putting it in `House` better at the time as it was easier to access from most places, but can change it if you want it to be in `Player`, its not too big of a difference either way.

**Comment by gereon77** [comment]
@Longwelwind From my feeling house also seems to be the better place. In case a player is replaced in future the replacing player will also be able to see it this way...
