### ISSUE TITLE
Bug in current productive PBEM game

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#293]
![image](https://user-images.githubusercontent.com/22304202/75990951-f9d97d00-5ef5-11ea-8e9d-af3b6b39254b.png)

https://swordsandravens.net/play/15441fca-b62b-41b2-abe6-0e71c4591455

Game cannot be loaded.

I guess it’s similar to the Crow killers bug. I lost a ship by retreating and it has been deleted but MapComponent.tsx still references this unit.

**Comment by gereon77** [comment]
Can't reproduce it on my machine with latest version. So I guess #280 already fixed that but isn't deployed yet.

**Comment by Longwelwind** [comment]
I found the error.

This is because, in the `houseCombatData.army` of Martell, there is the unit with the id `21`. When deserializing, the game looks for a unit with this id in the region of Martell (in this case, it was Port of Sunspear). But since we were in the resolution of Patchface ability, after the combat that Martell won, their units were no longer in Port of Sunspear but in East Summersea. Thus the error.

To solve this, the game should look in all regions when deserializing `houseCombatData.army`. I'll make a PR for that!

**Comment by gereon77** [comment]
Many thanks for fixing it this fast and we can continue...
