### ISSUE TITLE
Time limit per move

### ISSUE THREAD

**Issue by andrii-boiko** [Longwelwind/swords-and-ravens#345]
Do you plan to implement time limitation per move?

**Comment by gereon77** [comment]
Interesting idea... What shall happen if time limit has exceeded? When vassals are implemented user might be converted to a vassal then.. but just skipping users move probably would result in imbalance as everyone will try to rush in the castles of the inactive user...

**Comment by Vynder** [comment]
it's better than ruining the game for other players because one of them decided not to play anymore :)

**Comment by Vynder** [comment]
and another cool feature can be sound notifications when player need to do some action

**Comment by gereon77** [comment]
> and another cool feature can be sound notifications when player need to do some action

There is already an issue open for that...

**Comment by Vynder** [comment]
It would be nice to have option (5 minutes, 10 minutes, 1 hour, 1 day and unlimited) to choose time limit per move while creating a game.

**Comment by Longwelwind** [comment]
Thanks for the suggestion!

The only issue I have with time limit is how to handle the action the user should take. Defining a default action for all game states would take a big amount of work to implement.

If we implement a kick system and the vassal system, then a time limit would be redundant because if a game happens to have an inactive player, the players can kick them and a vassal would take their place.

Either way, I'll keep the issue open since the idea is interesting. If I ever implement a feature that makes this redundant, I'll close.

**Comment by aj-read** [comment]
This could tie in with this idea: https://github.com/Longwelwind/swords-and-ravens/issues/384

Once a player has exceeded the time limit, they are kicked/can be kicked by the host, and the ‘needs replacement’ tag comes up on the game

**Comment by gereon77** [comment]
Finally solved by #1486
