### ISSUE TITLE
Rewrite the code to handle ships left in a port after a march resolution

### ISSUE THREAD

**Issue by Longwelwind** [Longwelwind/swords-and-ravens#377]
Created after #376

**Comment by gereon77** [comment]
From my point of view the current handling is correct though it looks like it could be optimized. But be aware that we have to do the removal of the ships when leaving a castle empty right in place where it is handled now because in case you trigger an attack but lose the battle you would retreat to the originating region and therefore the ship wouldn't be destroyed by `isTakeControlOfEnemyPortGameStateRequired()` which would be against the rules.

**Comment by gereon77** [comment]
But there is one thing which right now came to my mind. We probably can remove the `destroyShipsIfNecessary()` method from `ResolveSingleMarchOrderGameState` and add a check in `isTakeControl...Required` if adjacent castle is uncontrolled or all units in it are wounded? What do you think?
