### ISSUE TITLE
Raven use is placed in the action phase on S&R, but should be during planning phase

### ISSUE THREAD

**Issue by Dode123** [Longwelwind/swords-and-ravens#448]

**Comment by Longwelwind** [comment]
Raven use shuld be done during the Planning Phase (which confirms that order restrictions due to Westeros cards are applied), but it is done during the Action phase in S&R because it was easier that way.

This means that during Raven use, the "Action" text in the top of the top-right panel will be highlighted, which is technically a bug.

It doesn't have any impact on the gameplay and I have no plan to fix this, so I'll put a `no fix` label on it!
