### ISSUE TITLE
Find a better way to represent wounded units

### ISSUE THREAD

**Issue by Longwelwind** [Longwelwind/swords-and-ravens#488]
At the moment, wounded units are shown slightly transparent compared than non-wounded units. It causes some issues among players who can't see them.

What other way could be used to represent wounded units?

I thought of a red cross across wounded units. It would be a bit big, but it would do the job.

**Comment by gereon77** [comment]
Using 3D units would allow to turning them upside down?

Like here: http://npiguet.github.io/agotmap/2ed.html

**Comment by Longwelwind** [comment]
I'm not fond of this idea for multiple reasons:

* I'm not fond of 3D units: the shapes of each unit types is pretty similar compared to the 2D units and they are bigger than the current ones.
* Putting a unit upside side doesn't convey that this unit wounded. Only someone who read somewhere that that's what an upside-down unit means would understand. A red cross would be more intuitive, I think.

**Comment by norielbit** [comment]
I did some experimentation with unit rotation, results are in this google drive folder:
https://drive.google.com/drive/folders/1Ab3_4o_pTue8wVkwA09JxuPuwZmvVM3j?usp=sharing

Changes from current:
- Non-routed units: unchanged
- Routed ground units: turned 90 degrees clockwise, increased opacity to 0.7
- Routed ships: unchanged

Code:
https://github.com/Longwelwind/swords-and-ravens/compare/master...norielbit:improve-wounded-unit

As for why ships are unchanged, its because I think they stand out enough over the blue-grey water texture, although it might change with Arryn's blue ships. Also, ports might require some touch up.

**Comment by Dode123** [comment]
Looks good. Though siege engines doesn't need a retreated stance, as they can never retreat. 😊

**Comment by Longwelwind** [comment]
I like putting units on the side.

My only grip is that we don't have something similar for ships. It's a bit inconsistent, and I feel like people will wonder why land units are on the side and not ships. But it's good for now!

Put a PR with your branch, and I'll review and merge this.

**Comment by norielbit** [comment]
I agree, but from the experimentation I did I couldn't get to something with the ships that "feels right" because they are kinda "directionless". Mirroring them horizontally was interesting, but still felt weird to me when having both routed and non-routed ships in the same area.

In the board game we usually put the standing up when routed, which could be done here with a simple square sprite but I feel like it would be more confusing than helpful

As for the PR, open it for `v1.5`, right?

**Comment by Longwelwind** [comment]
For ships, maybe having them straight up, instead of diagonally, and then having them stand down when wounded would be better. But that's a talk for a later issue/PR.

You can put it in `master`, it poses some problem for players, so we can consider it urgent. 🙂

**Comment by norielbit** [comment]
Sure, I'll open it right away.

Just for reference, that's how it looks for horizontal flip:
![image](https://user-images.githubusercontent.com/18612633/79205155-404fbf00-7e46-11ea-9eb6-0552b476cf45.png)

**Comment by Longwelwind** [comment]
Indeed, it's ugly 😆

**Comment by Longwelwind** [comment]
The current way is good enough for a long time, I think.

I'll close this issue.
