### ISSUE TITLE
Implement tides of battle

### ISSUE THREAD

**Issue by mrhappyasthma** [Longwelwind/swords-and-ravens#561]
- Adding some way to enable Tides of Battle mode from the lobby screen of the website
- Requires adding scans of all the cards as images
- Adds some logic to the battle, which triggers after house card reveal

Details on page 29 of the [rulebook](https://images-cdn.fantasyflightgames.com/filer_public/30/4f/304f72e3-4fe4-4f91-bfbe-75133161b092/va65_agot2_rulebook_web.pdf).

**Comment by Longwelwind** [comment]
This is planned, but no in the foreseeable roadmap at the moment as other features like Vassals are, I think, more wanted. 🙂

**Comment by mrhappyasthma** [comment]
I'll take a stab at this. :)

**Comment by Longwelwind** [comment]
The biggest hurdle to implement this is that we don't handle winner casualties at the moment, which is something that is required by Tides of Battle cards (since skulls inflict casualties whatever the winner/loser of the fight).

There is a `ChooseCasualtiesGameState`, though, and I think it should be possible to re-use it to handle winner casualties. In the code, you can compute the number of casualties for the winner first, if it is `> 0`, proceed to the aforementionned game state, then in `onChooseCasulaltiesGameStateEnd`, check if the house is the winner, if it is, then compute the number of casualties of the loser, and go to the same game state if it is `> 0`.

The only state that will need to be added is the 2 ToB cards that have been drawn (they can be added in the object inside `houseCombatDatas` in `CombatGameState`). They must be serialized/deserialized. Normally, nothing else should be needed.
