### ISSUE TITLE
Lowest bidder effect of „The horde descends“ allows to pick 2 units from different castles

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#604]
![ED88389A-207B-40D9-95F1-51E2CA48D0A4](https://user-images.githubusercontent.com/22304202/80858977-a23d6080-8c5d-11ea-8e10-b568c5211fdf.jpeg)

**Comment by Dode123** [comment]
Also:
If the lowest bidder does not have two units at any castle/stronghold area, he can perform the action as all the other houses (**anywhere**). Just that he needs to pick two units, instead of one.

**Comment by gereon77** [comment]
As this text is printed on the card I thought it’s not necessary to explicitly mention it 😬but thx you are right

**Comment by Dode123** [comment]
Well there seemed to be some conflict, since you said on Discord "I would assume when a player has not two units in a castle he has to remove units in castles before removing units in non castle areas. But from the card text the „if unable“ then says anywhere...". 

But I thought about it and it must be anywhere. :P

**Comment by gereon77** [comment]
Yea from the current definition definitely.. but an errata b3 could define at least from one castle if able or similar...

**Comment by gereon77** [comment]
Grabbed
