### ISSUE TITLE
Massing on the Milkwater doesn't handle discarding of the last two cards with same strength correctly

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#632]
![image](https://user-images.githubusercontent.com/22304202/81606465-734c8a80-93d3-11ea-8dbe-87a1eb19c59c.png)

You can run in the situation that you don't have a card to choose:

![image](https://user-images.githubusercontent.com/22304202/81606543-924b1c80-93d3-11ea-8319-3a93c494c494.png)

![image](https://user-images.githubusercontent.com/22304202/81606590-a7c04680-93d3-11ea-8cf4-4b6821e8395e.png)

**Comment by gereon77** [comment]
That's the first time where I would differ from the rulebook and implement it the way that the user has to keep both cards, like it is the case when he has only one as the official definition is no punishment for the lowest bidder, it refreshes his weak hand...

**Comment by Longwelwind** [comment]
I'd let the player keep the 2 cards in this situation, it feels to me to be the best way to handle this, and the more inline with the way the designers made the card. It's hard to judge without input from the designer, but I feel like it's more in the intent of the card than what is proposed from the errata.

We can see later if it's better to implement the more complex handling. Sorry to say that since I saw you already implemented this flow. 😨

**Comment by gereon77** [comment]
That’s absolutely no problem! TBH I like your decision to differ from the rules here! I just had time yesterday and thought without your input I start fixing it according to the rules. If you agree I will save my work on a separate branch and change the PR according to your suggestion...
