### ISSUE TITLE
can't refuse automatic support

### ISSUE THREAD

**Issue by vivard** [Longwelwind/swords-and-ravens#753]
I had Greyjoy on the party https://swordsandravens.net/play/d3174241-2e86-45bb-891a-cd1746ae3bb4, and  I can't refuse my automatic support, then the power of asha couldn't activate. 

It was the last fight of round 7

**Comment by gereon77** [comment]
Hi! Thanks for your report. Was the button disabled? Nevertheless Ashas ability would have only worked if you would have won the fight and the support didn't matter here....

**Comment by vivard** [comment]
Didn't see any disabled button. Asha power didn't need to won the fight, just to have no support


Le 27 oct. 2020 à 07:33, à 07:33, gereon77 <notifications@github.com> a écrit:

**Comment by gereon77** [comment]
> Didn't see any disabled button. Asha power didn't need to won the fight, just to have no support 

Yea you are right! I forgot that Asha gets a tower also for not being supported which works also when defending.

But can you explain, why you weren't able to refuse your support? I guess the problem is you misunderstood the work flow. During house card selection there is an additional option "Refuse granted support". As soon as you have choosen your house card, this option gets disabled.

**Comment by vivard** [comment]
You must be right, I didn't pay attention to the additional option "Refuse granted support". Thank's
