### ISSUE TITLE
Add sound & visual notification when it is a player's turn

### ISSUE THREAD

**Issue by Longwelwind** [Longwelwind/swords-and-ravens#80]

**Comment by gereon77** [comment]
And a visual also..

**Comment by Longwelwind** [comment]
Possible ideas for visual notifications:

* Change the favicon (the icon in the tab bar of the browser) with a small dot to indicate that it is the player's turn.
* Put the upper-right panel with a slight yellow glow to indicate that the player can do an action.

**Comment by gereon77** [comment]
> 
> 
> Possible ideas for visual notifications:
> 
>     * Change the favicon (the icon in the tab bar of the browser) with a small dot to indicate that it is the player's turn.
> 
>     * Put the upper-right panel with a slight yellow glow to indicate that the player can do an action.

Favicon is good when you are in an other tab. But I guess browsers don't reload them when the tab is not active... At least it could be tried. But when you are on the page playing a live game I guess this is not enough because users don't care for the favicon. It's not in the users default view.

Glowing the upper right panel might be enough for desktop but you don't see that on mobile all the time... It should be sth which jump into your eyes... That's why i suggested background change.. But probably that feels crappy for the eyes also...

**Comment by Longwelwind** [comment]
Retained sound for the notification: https://notificationsounds.com/message-tones/open-up-587
